--- 
 - hosts: local
   become: yes
   become_user: root
   
   tasks:

    - name: Creación del contenedor Lisa
      lxc_container:
        name: lisa
        container_log: true
        template: centos
        state: started